import { useState, useEffect } from "react";
import api from "../api/axios";
import {
  Calendar,
  Save,
  RefreshCw,
  LayoutGrid,
  List as ListIcon,
} from 'lucide-react';
import { Table, Button, Card, Form, Spinner, Alert, Badge } from 'react-bootstrap';
import { useNavigate, useLocation } from 'react-router-dom';

const JOURS = ["LUNDI", "MARDI", "MERCREDI", "JEUDI", "VENDREDI", "SAMEDI"];
const SLOTS = [
  { start: "08:30", end: "10:30", label: "08:30 - 10:30" },
  { start: "10:30", end: "13:00", label: "10:30 - 13:00" },
  { start: "13:30", end: "16:30", label: "13:30 - 16:30" },
  { start: "16:30", end: "18:30", label: "16:30 - 18:30" },
];

const AutomatedSchedule = () => {
  // Calcule le lundi de la semaine courante
  // Si on est dimanche, on prend le lundi de la semaine suivante (demain)
  const getTodayMonday = () => {
    const today = new Date();
    const day = today.getDay();
    const diffToMonday = day === 0 ? 1 : 1 - day;
    const monday = new Date(today);
    monday.setDate(today.getDate() + diffToMonday);
    const year  = monday.getFullYear();
    const month = String(monday.getMonth() + 1).padStart(2, '0');
    const date  = String(monday.getDate()).padStart(2, '0');
    return `${year}-${month}-${date}`;
  };

  const navigate = useNavigate();
  const location = useLocation();

  const [weekStart, setWeekStart] = useState(() => {
    if (location.state?.week) {
      return location.state.week;
    }
    return getTodayMonday();
  });
  const [loading, setLoading] = useState(false);
  const [schedule, setSchedule] = useState([]);
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(null);
  const [viewMode, setViewMode] = useState('grid'); // 'table' or 'grid'

  // Data for editing
  const [formateurs, setFormateurs] = useState([]);
  const [salles, setSalles] = useState([]);
  const [modules, setModules] = useState([]);
  const [groupes, setGroupes] = useState([]);

  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  useEffect(() => {
    fetchBaseData();
  }, []);

  useEffect(() => {
    if (location.state?.week) {
      setWeekStart(location.state.week);
    }
  }, [location.state]);

  const fetchBaseData = async () => {
    try {
      const [f, s, m, g] = await Promise.all([
        api.get('/formateurs'),
        api.get('/salles'),
        api.get('/modules'),
        api.get('/groupes')
      ]);
      setFormateurs(f.data.data || f.data);
      setSalles(s.data.data || s.data);
      setModules(m.data.data || m.data);
      setGroupes(g.data.data || g.data);
    } catch (err) {
      console.error("Error fetching base data", err);
    }
  };

  const handleGenerate = async () => {
    if (!weekStart) {
      setError("Veuillez choisir une date de début de semaine.");
      return;
    }

    setLoading(true);
    setError(null);
    setSchedule([]);

    try {
      const response = await api.post('/generate-schedule', {
        week_start: weekStart,
        algo: 'ga'
      });

      if (response.data.success) {
        setSchedule(response.data.schedule);
        setSuccess("Emploi du temps généré avec succès !");
      } else {
        setError(response.data.message || "Erreur lors de la génération.");
      }
    } catch (err) {
      setError(err.message || "Impossible de contacter le service de génération.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (location.state?.autoGenerate && !hasAutoGenerated && weekStart) {
      setHasAutoGenerated(true);
      handleGenerate();
    }
  }, [location.state, weekStart, hasAutoGenerated]);

  const handleSaveAll = async () => {
    setLoading(true);
    try {
      const response = await api.post('/save-schedule', {
        schedule: schedule
      });
      if (response.data.success) {
        setSuccess(response.data.message);
        setSchedule([]); // Clear after save
        setTimeout(() => {
          navigate("/emploi-formateur", { state: { week: weekStart } });
        }, 1500);
      }
    } catch (err) {
      console.error(err);
      if (err.response?.data) {
        setError("Erreur: " + (err.response.data.message || JSON.stringify(err.response.data)));
      } else {
        setError("Erreur lors de l'enregistrement final: " + err.message);
      }
    } finally {
      setLoading(false);
    }
  };

  const getDayName = (dateStr) => {
    const date = new Date(dateStr);
    const day = date.getDay();
    return JOURS[day === 0 ? 5 : day - 1];
  };

  const getSeanceForGrid = (formateurId, jour, slotStart) => {
    return schedule.find(s =>
      s.formateur_id === Number.parseInt(formateurId) &&
      getDayName(s.date) === jour &&
      s.debut === slotStart
    );
  };

  return (
    <div className="p-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <div>
          <h2 className="fw-bold text-primary mb-0">
            <RefreshCw className="me-2" size={28} />
            Génération Automatisée
          </h2>
        </div>

        <Card className="shadow-sm border-0">
          <Card.Body className="p-3 d-flex align-items-center gap-3">
            <div className="d-flex flex-column">
              <label htmlFor="week-start" className="text-uppercase text-muted fw-bold" style={{ fontSize: '10px' }}>Semaine du</label>
              <Form.Control
                id="week-start"
                type="date"
                size="sm"
                value={weekStart}
                onChange={(e) => setWeekStart(e.target.value)}
              />
            </div>
            <Button
              variant="primary"
              onClick={handleGenerate}
              disabled={loading}
              className="d-flex align-items-center gap-2"
            >
              {loading ? <Spinner animation="border" size="sm" /> : <RefreshCw size={18} />}
              {loading ? "Calcul en cours..." : "Générer"}
            </Button>
          </Card.Body>
        </Card>
      </div>

      {error && <Alert variant="danger" onClose={() => setError(null)} dismissible>{error}</Alert>}
      {success && <Alert variant="success" onClose={() => setSuccess(null)} dismissible>{success}</Alert>}

      {schedule.length > 0 && (
        <div className="mb-4">
          <div className="d-flex justify-content-between align-items-center mb-3">
            <div className="btn-group shadow-sm">
              <Button
                variant={viewMode === 'grid' ? 'dark' : 'outline-dark'}
                size="sm"
                onClick={() => setViewMode('grid')}
              >
                <LayoutGrid size={16} className="me-1" /> Grille Staff
              </Button>
              <Button
                variant={viewMode === 'table' ? 'dark' : 'outline-dark'}
                size="sm"
                onClick={() => setViewMode('table')}
              >
                <ListIcon size={16} className="me-1" /> Liste Détails
              </Button>
            </div>
          </div>

          {/* Bouton d'enregistrement flottant à droite */}
          <Button 
            variant="success" 
            onClick={handleSaveAll} 
            className="position-fixed shadow-lg fw-bold d-flex align-items-center animate__animated animate__bounceIn"
            style={{ 
              right: '30px', 
              bottom: '30px', 
              zIndex: 1050, 
              padding: '15px 25px', 
              borderRadius: '50px',
              border: '4px solid white'
            }}
          >
            <Save size={20} className="me-2" /> 
            Enregistrer l'emploi
          </Button>

          <Card className="shadow-sm border-0 overflow-hidden">
            <Card.Body className="p-0">
              {viewMode === 'table' ? (
                <Table responsive hover className="mb-0 align-middle">
                  <thead className="bg-light">
                    <tr>
                      <th className="px-4">Date & Heure</th>
                      <th>Groupe</th>
                      <th>Module</th>
                      <th>Formateur</th>
                      <th>Salle</th>
                      <th className="text-center">Type</th>
                    </tr>
                  </thead>
                  <tbody>
                    {schedule.map((item, index) => (
                      <tr key={`${item.date}-${item.groupe_id}-${item.module_id}-${item.debut}`}>
                        <td className="px-4">
                          <div className="fw-bold">{item.date}</div>
                          <small className="text-muted">{item.debut} - {item.fin}</small>
                        </td>
                        <td><Badge bg="secondary">{groupes.find(g => g.id === item.groupe_id)?.nom}</Badge></td>
                        <td className="small">{modules.find(m => m.id === item.module_id)?.nom}</td>
                        <td>
                          {(() => {
                            const f = formateurs.find(prof => prof.id === item.formateur_id);
                            return f ? `${f.nom} ${f.prenom || ""}`.trim() : "";
                          })()}
                        </td>
                        <td><Badge bg="info" text="dark">{salles.find(s => s.id === item.salle_id)?.nom}</Badge></td>
                        <td className="text-center">
                          <Badge bg={item.type === 'efm' ? 'warning' : 'primary'} className="text-uppercase">
                            {item.type}
                          </Badge>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </Table>
              ) : (
                <div className="table-responsive" style={{ maxHeight: '80vh' }}>
                  <Table bordered size="sm" className="mb-0 text-center table-sticky-header" style={{ minWidth: '1600px', fontSize: '10px' }}>
                    <thead className="table-dark">
                      <tr>
                        <th rowSpan={2} className="align-middle sticky-col-header" style={{ width: '120px' }}>Enseignants</th>
                        {JOURS.map(j => (
                          <th key={j} colSpan={SLOTS.length} className="text-center py-2 border-secondary">
                            {j}
                          </th>
                        ))}
                      </tr>
                      <tr>
                        {JOURS.map(j => SLOTS.map(slot => (
                          <th key={`${j}-${slot.start}`} className="border-secondary fw-normal" style={{ fontSize: '9px' }}>{slot.label}</th>
                        )))}
                      </tr>
                    </thead>
                    <tbody>
                      {formateurs.map(prof => (
                        <tr key={prof.id}>
                          <td className="fw-bold bg-light align-middle sticky-col">
                            {prof.nom} {prof.prenom || ""}
                          </td>
                          {JOURS.map(jour =>
                            SLOTS.map(slot => {
                              const seance = getSeanceForGrid(prof.id, jour, slot.start);
                              if (seance) {
                                return (
                                  <td key={`${prof.id}-${jour}-${slot.start}`} className="p-1 align-middle" style={{ minWidth: '140px' }}>
                                    <div className={`p-1 rounded border text-start shadow-sm ${seance.type === 'efm' ? 'bg-warning-subtle border-warning' : 'bg-white border-light-subtle'}`}>
                                      <div className="fw-bold text-primary mb-1" style={{ fontSize: '10px' }}>{groupes.find(g => g.id === seance.groupe_id)?.nom}</div>
                                      <div className="text-muted text-truncate mb-1" style={{ fontSize: '9px' }} title={modules.find(m => m.id === seance.module_id)?.nom}>
                                        {modules.find(m => m.id === seance.module_id)?.nom}
                                      </div>
                                      <div className="d-flex justify-content-between align-items-center mt-1">
                                        <span className="fw-bold text-success" style={{ fontSize: '9px' }}>{salles.find(s => s.id === seance.salle_id)?.nom}</span>
                                        {seance.type !== 'cours' && <Badge bg="secondary" style={{ fontSize: '7px' }}>{seance.type.toUpperCase()}</Badge>}
                                      </div>
                                    </div>
                                  </td>
                                );
                              }
                              return <td key={`${prof.id}-${jour}-${slot.start}`} className="bg-light-subtle"></td>;
                            })
                          )}
                        </tr>
                      ))}
                    </tbody>
                  </Table>
                </div>
              )}
            </Card.Body>
          </Card>
        </div>
      )}

      {!loading && schedule.length === 0 && (
        <div className="text-center py-5">
          <div className="mb-3 text-muted opacity-25">
            <Calendar size={64} />
          </div>
          <h4 className="text-muted">Prêt pour la génération</h4>
          <p className="text-muted small">Choisissez une date et lancez la génération.</p>
        </div>
      )}

      <style>{`
        .table-sticky-header thead th {
          position: sticky;
          top: 0;
          z-index: 10;
          background-color: #212529 !important;
          color: white;
        }
        .table-sticky-header thead tr:nth-child(2) th {
          top: 34px;
        }
        .table-sticky-header .sticky-col {
          position: sticky;
          left: 0;
          z-index: 5;
          background-color: #f8f9fa !important;
          border-right: 2px solid #dee2e6 !important;
        }
        .table-sticky-header .sticky-col-header {
          position: sticky;
          left: 0;
          top: 0;
          z-index: 15 !important;
          background-color: #212529 !important;
        }
      `}</style>
    </div>
  );
};

export default AutomatedSchedule;
